# Generated by Django 6.0.2 on 2026-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_emailvalidationresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailvalidationresult',
            new_name='accounts_em_history_9f80d3_idx',
            old_name='accounts_em_histori_18fbb8_idx',
        ),
        migrations.RenameIndex(
            model_name='emailvalidationresult',
            new_name='accounts_em_history_c8b27c_idx',
            old_name='accounts_em_histori_0347ad_idx',
        ),
        migrations.AddField(
            model_name='emailvalidationresult',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
