# Generated by Django 6.1 on 2026-08-24 05:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_emailvalidationhistory_report_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidationhistory',
            name='request_id',
            field=models.CharField(blank=True, default=accounts.models.generate_email_validation_request_id, max_length=80, unique=True),
        ),
    ]
