# Generated by Django 6.1 on 2026-09-23 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_emailvalidationhistory_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=150)),
                ('business_category', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(default='WhatsApp Business', max_length=50)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('whatsapp_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
