# Generated by Django 6.1 on 2026-09-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_whatsappaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=30)),
                ('number_type', models.CharField(default='WhatsApp Number', max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('business_category', models.CharField(default='Business', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_numbers', to='accounts.whatsappaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsAppAccounts',
        ),
    ]
