from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    SignupView, OTPVerifyView, LoginView,
    ForgotPasswordView, ResetPasswordView, ResendOTPView,
    UserProfileView, AdminUsersListView, AdminUsersExportView, AdminUserPermissionView,
    SMSSendView, SMSMessageListView, SMSMessageStatusView,
    SMSCredentialView, UserSMSEligibilityView, AdminUsersSMSListView,
    SMSContactGroupView, SMSShortURLView, SMSShortURLDetailView,
    SMSTimezoneListView,
    FreeTrialSendOTPView, FreeTrialVerifyOTPView, FreeTrialVerifiedNumbersView,
    FreeTrialSendSMSView, SMSUsageSummaryView,
    AdminNotificationPreviewView, AdminNotificationSendView,
    AdminNotificationHistoryView, UserNotificationListView,
    UserNotificationReadView,
    ConfirmAdminPromotionView,
    EmailValidationView,
    UserWalletView,
    WalletRechargeConfigView,
    WalletRechargeCreateOrderView,
    WalletRechargeVerifyView,
    WalletRechargePaymentListView,
    UserAPIKeyListCreateView,
    UserAPIKeyDetailView,
    APIEmailValidationView,
    EmailValidationStatusView,
    EmailValidationResultsListView,
    EmailValidationControlView,
    APIEmailValidationStatusView,
    APIEmailValidationControlView,
    SendDeliverableEmailsView,
    ValidationHistoryListView,
    AdminLatestValidationHistoryView,
    AdminUserValidationHistoryView,
    AdminOwnSystemValidationDiagnosticsView,
    AdminCreditSettingsView,
    AdminRechargeChargeSettingsView,
    AdminUserWalletCreditsView,
    EmailValidationIPWhitelistRequestView,
    AdminEmailValidationIPWhitelistRequestListView,
    AdminEmailValidationIPWhitelistRequestDetailView,
    AdminEmailValidationAssignWhitelistIPView,
    RequestStatusSearchView,
    SenderIdRequestView,
    AdminSenderIdRequestListView,
    AdminSenderIdRequestDetailView,
    EmployeeSignupView,
    EmployeeVerifyDualOTPView,
    EmployeeLoginView,
    AdminEmployeeListView,
)
from .download_views import (
    EmailValidationDownloadView,
    EmailValidationReportDownloadView,
)

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('verify-otp/', OTPVerifyView.as_view(), name='verify-otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend-otp'),
    path('login/', LoginView.as_view(), name='login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('admin/users/', AdminUsersListView.as_view(), name='admin-users'),
    path('admin/users/<int:user_id>/permissions/', AdminUserPermissionView.as_view(), name='admin-user-permissions'),
    path('admin/users/export/', AdminUsersExportView.as_view(), name='admin-users-export'),
    path('confirm-admin-promotion/', ConfirmAdminPromotionView.as_view(), name='confirm-admin-promotion'),
    
    # SMS endpoints
    path('sms/send/', SMSSendView.as_view(), name='sms-send'),
    path('sms/messages/', SMSMessageListView.as_view(), name='sms-messages'),
    path('sms/messages/<int:pk>/', SMSMessageStatusView.as_view(), name='sms-status'),
    path('sms/credentials/', SMSCredentialView.as_view(), name='sms-credentials'),
    path('sms/users/<int:user_id>/eligibility/', UserSMSEligibilityView.as_view(), name='sms-eligibility'),
    path('sms/admin/users/', AdminUsersSMSListView.as_view(), name='sms-admin-users'),
    path('sms/groups/', SMSContactGroupView.as_view(), name='sms-groups'),
    path('sms/short-urls/', SMSShortURLView.as_view(), name='sms-short-urls'),
    path('sms/short-urls/<int:url_id>/', SMSShortURLDetailView.as_view(), name='sms-short-url-detail'),
    path('sms/timezones/', SMSTimezoneListView.as_view(), name='sms-timezones'),
    path('sms/usage-summary/', SMSUsageSummaryView.as_view(), name='sms-usage-summary'),
    path('sms/free-trial/send-otp/', FreeTrialSendOTPView.as_view(), name='sms-free-trial-send-otp'),
    path('sms/free-trial/verify-otp/', FreeTrialVerifyOTPView.as_view(), name='sms-free-trial-verify-otp'),
    path('sms/free-trial/verified-numbers/', FreeTrialVerifiedNumbersView.as_view(), name='sms-free-trial-verified-numbers'),
    path('sms/free-trial/send/', FreeTrialSendSMSView.as_view(), name='sms-free-trial-send'),
    path('sms/sender-id-requests/', SenderIdRequestView.as_view(), name='sms-sender-id-requests'),
    path('sms/admin/sender-id-requests/', AdminSenderIdRequestListView.as_view(), name='admin-sms-sender-id-requests'),
    path('sms/admin/sender-id-requests/<int:pk>/', AdminSenderIdRequestDetailView.as_view(), name='admin-sms-sender-id-request-detail'),

    # Email validation platform endpoints
    path('wallet/', UserWalletView.as_view(), name='wallet'),
    path('wallet/recharge/config/', WalletRechargeConfigView.as_view(), name='wallet-recharge-config'),
    path('wallet/recharge/create-order/', WalletRechargeCreateOrderView.as_view(), name='wallet-recharge-create-order'),
    path('wallet/recharge/verify/', WalletRechargeVerifyView.as_view(), name='wallet-recharge-verify'),
    path('wallet/recharge/payments/', WalletRechargePaymentListView.as_view(), name='wallet-recharge-payments'),
    path('email-validation/validate/', EmailValidationView.as_view(), name='email-validation-validate'),
    path('email-validation/history/', ValidationHistoryListView.as_view(), name='email-validation-history'),
    path('email-validation/ip-whitelist-requests/', EmailValidationIPWhitelistRequestView.as_view(), name='email-validation-ip-whitelist-requests'),
    path('email-validation/history/<str:request_id>/status/', EmailValidationStatusView.as_view(), name='email-validation-status'),
    path('email-validation/history/<str:request_id>/results/', EmailValidationResultsListView.as_view(), name='email-validation-results'),
    path('email-validation/history/<str:request_id>/download/', EmailValidationDownloadView.as_view(), name='email-validation-download'),
    path('email-validation/reports/download/', EmailValidationReportDownloadView.as_view(), name='email-validation-report-download'),
    path('email-validation/history/<str:request_id>/control/', EmailValidationControlView.as_view(), name='email-validation-control'),
    path('email-validation/send-deliverable-mails/', SendDeliverableEmailsView.as_view(), name='email-validation-send-deliverable-mails'),
    path('email-validation/api-keys/', UserAPIKeyListCreateView.as_view(), name='email-validation-api-keys'),
    path('email-validation/api-keys/<uuid:key_id>/', UserAPIKeyDetailView.as_view(), name='email-validation-api-key-detail'),
    path('email-validation/api/validate/', APIEmailValidationView.as_view(), name='email-validation-api-validate'),
    path('email-validation/api/status/', APIEmailValidationStatusView.as_view(), name='email-validation-api-status'),
    path('email-validation/api/control/', APIEmailValidationControlView.as_view(), name='email-validation-api-control'),
    path('admin/email-validation/history/latest/', AdminLatestValidationHistoryView.as_view(), name='admin-email-validation-history-latest'),
    path('admin/email-validation/history/users/<int:user_id>/', AdminUserValidationHistoryView.as_view(), name='admin-email-validation-history-user'),
    path('admin/email-validation/own-system-diagnostics/', AdminOwnSystemValidationDiagnosticsView.as_view(), name='admin-email-validation-own-system-diagnostics'),
    path('admin/email-validation/credit-settings/', AdminCreditSettingsView.as_view(), name='admin-email-validation-credit-settings'),
    path('admin/email-validation/ip-whitelist-requests/', AdminEmailValidationIPWhitelistRequestListView.as_view(), name='admin-email-validation-ip-whitelist-requests'),
    path('admin/email-validation/ip-whitelist-requests/<int:pk>/', AdminEmailValidationIPWhitelistRequestDetailView.as_view(), name='admin-email-validation-ip-whitelist-request-detail'),
    path('admin/email-validation/ip-whitelist/assign/', AdminEmailValidationAssignWhitelistIPView.as_view(), name='admin-email-validation-ip-whitelist-assign'),
    path('admin/wallet/recharge-settings/', AdminRechargeChargeSettingsView.as_view(), name='admin-wallet-recharge-settings'),
    path('admin/users/<int:user_id>/wallet/credits/', AdminUserWalletCreditsView.as_view(), name='admin-user-wallet-credits'),
    path('request-status/search/', RequestStatusSearchView.as_view(), name='request-status-search'),

    # Employee auth flow
    path('employee/signup/', EmployeeSignupView.as_view(), name='employee-signup'),
    path('employee/verify-dual-otp/', EmployeeVerifyDualOTPView.as_view(), name='employee-verify-dual-otp'),
    path('employee/login/', EmployeeLoginView.as_view(), name='employee-login'),
    path('admin/employees/', AdminEmployeeListView.as_view(), name='admin-employees-list'),

    # Internal notifications (no external credentials required)
    path('admin/notifications/preview/', AdminNotificationPreviewView.as_view(), name='admin-notifications-preview'),
    path('admin/notifications/send/', AdminNotificationSendView.as_view(), name='admin-notifications-send'),
    path('admin/notifications/history/', AdminNotificationHistoryView.as_view(), name='admin-notifications-history'),
    path('notifications/my/', UserNotificationListView.as_view(), name='notifications-my-list'),
    path('notifications/my/<int:recipient_id>/read/', UserNotificationReadView.as_view(), name='notifications-my-read'),
]


